[project]

site_name = "Coyote Claw"
site_description = "DG-LAB Coyote 3.0 第三方控制器"
site_author = "qiekn"
site_url = "https://qiekn.github.io/coyote-claw/"
repo_url = "https://github.com/qiekn/coyote-claw"

nav = [
  { "首页" = "index.md" },
  { "架构" = "project.md" },
  { "波形数据" = "json.md" },
  { "波形文件" = "pulse.md" },
]

[project.theme]

logo = "images/zensical.svg"
favicon = "images/zensical.png"
language = "zh"

features = [
    "announce.dismiss",
    "content.code.annotate",
    "content.code.copy",
    "content.code.select",
    "content.footnote.tooltips",
    "content.tabs.link",
    "content.tooltips",
    "navigation.footer",
    "navigation.indexes",
    "navigation.instant",
    "navigation.instant.prefetch",
    "navigation.path",
    "navigation.sections",
    "navigation.top",
    "navigation.tracking",
    "search.highlight",
    "toc.integrate",
]

[[project.theme.palette]]
media = "(prefers-color-scheme: light)"
scheme = "default"
toggle.icon = "lucide/sun"
toggle.name = "Switch to dark mode"

[[project.theme.palette]]
media = "(prefers-color-scheme: dark)"
scheme = "slate"
toggle.icon = "lucide/moon"
toggle.name = "Switch to light mode"

[[project.extra.social]]
icon = "fontawesome/brands/github"
link = "https://github.com/qiekn/coyote-claw"

[project.markdown_extensions.pymdownx.highlight]
pygments_lang_class = true
[project.markdown_extensions.pymdownx.superfences]
[project.markdown_extensions.admonition]
